version: "3.8"
services:
  mongo:
    image: mongo:7
    restart: always
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_DATABASE: planbana
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express:1.0.2-20
    restart: always
    ports: ["8081:8081"]
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
volumes:
  mongo_data:
