// package com.planbana.backend.audit;

// public enum AuditAction {

//     // ============================
//     // ADMIN ACTIONS
//     // ============================
//     ADMIN_LOGIN,
//     ADMIN_LOGOUT,
//     ADMIN_CREATED_USER,
//     ADMIN_DELETED_USER,
//     ADMIN_UPDATED_USER_PROFILE,
//     ADMIN_RESET_USER_PASSWORD,
//     ADMIN_UPDATED_USER_ROLE,
//     ADMIN_VERIFICATION_APPROVED,
//     ADMIN_VERIFICATION_REJECTED,
//     ADMIN_REVIEWED_REPORT,

//     ADMIN_CREATED_EVENT,
//     ADMIN_UPDATED_EVENT_DETAILS,
//     ADMIN_DELETED_EVENT,
//     ADMIN_BLOCKED_EVENT,
//     ADMIN_UNBLOCKED_EVENT,
//     ADMIN_HIDDEN_EVENT,
//     ADMIN_UNHIDDEN_EVENT,
//     ADMIN_APPROVED_EVENT,
//     ADMIN_FEATURED_EVENT,

//     ADMIN_UPDATED_SYSTEM_SETTINGS,
//     ADMIN_UPDATED_FEATURE_FLAGS,
//     ADMIN_UPDATED_LIMITS,
//     ADMIN_UPDATED_MAINTENANCE_MODE,
//     ADMIN_UPDATED_ANNOUNCEMENT,

//     // ============================
//     // USER ACCOUNT / PROFILE
//     // ============================
//     USER_REGISTERED,
//     USER_LOGGED_IN,
//     USER_LOGGED_OUT,
//     USER_PROFILE_UPDATED,
//     USER_PHONE_UPDATED,
//     USER_EMAIL_UPDATED,
//     USER_PASSWORD_CHANGED,
//     USER_ACCOUNT_DISABLED,
//     USER_ACCOUNT_REACTIVATED,
//     USER_GOV_ID_SUBMITTED,
//     USER_GOV_ID_VERIFIED,
//     USER_GOV_ID_REJECTED,

//     // ============================
//     // USER ACTIVITY ON EVENTS
//     // ============================
//     USER_CREATED_EVENT,
//     USER_UPDATED_EVENT,
//     USER_DELETED_EVENT,
//     USER_BOOKMARKED_EVENT,
//     USER_REMOVED_BOOKMARK,
//     USER_LEFT_EVENT,
//     USER_UPLOADED_EVENT_IMAGE,

//     // ============================
//     // EVENT LIFE CYCLE
//     // ============================
//     EVENT_CREATED,
//     EVENT_DETAILS_UPDATED,
//     EVENT_IMAGE_UPDATED,
//     EVENT_LOCATION_UPDATED,
//     EVENT_TIME_UPDATED,
//     EVENT_CANCELED,
//     EVENT_RESTORED,
//     EVENT_AUTO_BLOCKED,
//     EVENT_AUTO_ARCHIVED,
//     EVENT_STARTED,
//     EVENT_ENDED,

//     // ============================
//     // EVENT JOIN / PARTICIPATION
//     // ============================
//     EVENT_JOIN_REQUESTED,
//     EVENT_JOIN_APPROVED,
//     EVENT_JOIN_REJECTED,
//     EVENT_JOIN_WAITLISTED,
//     EVENT_JOIN_CANCELLED,
//     EVENT_PARTICIPANT_REMOVED,
//     EVENT_COHOST_ADDED,
//     EVENT_COHOST_REMOVED,

//     // ============================
//     // EVENT REACTIONS
//     // ============================
//     EVENT_LIKED,
//     EVENT_UNLIKED,

//     // ============================
//     // REPORTING & MODERATION
//     // ============================
//     USER_REPORTED_USER,
//     USER_REPORTED_EVENT,
//     REPORT_REVIEWED_BY_ADMIN,
//     REPORT_ACTION_TAKEN,
//     EVENT_FLAGGED_BY_USER,

//     // ============================
//     // SECURITY & FRAUD
//     // ============================
//     MULTIPLE_FAILED_LOGIN_ATTEMPTS,
//     UNUSUAL_LOCATION_LOGIN,
//     TOKEN_TAMPER_DETECTED,
//     EXPIRED_TOKEN_USED,
//     INVALID_TOKEN_ATTEMPT,
//     UNAUTHORIZED_ACCESS_ATTEMPT,
//     FORBIDDEN_ADMIN_ACCESS_ATTEMPT,
//     API_RATE_LIMIT_EXCEEDED,
//     IP_BLOCKED_DUE_TO_ABUSE,
//     MULTIPLE_PASSWORD_RESET_REQUESTS,
//     SUSPICIOUS_EVENT_SPAM,

//     // ============================
//     // PAYMENTS
//     // ============================
//     PAYMENT_INITIATED,
//     PAYMENT_SUCCESS,
//     PAYMENT_FAILED,
//     REFUND_INITIATED,
//     REFUND_COMPLETED,

//     // ============================
//     // INTEGRATIONS
//     // ============================
//     SMS_SENT,
//     PUSH_NOTIFICATION_SENT,
//     EMAIL_SENT,
//     FAILED_TO_SEND_EMAIL,
//     FAILED_TO_SEND_PUSH,
//     FIREBASE_LOGIN_FAILURE,

//     // ============================
//     // SYSTEM
//     // ============================
//     SYSTEM_CRON_EXECUTED,
//     SYSTEM_MAINTENANCE_STARTED,
//     SYSTEM_MAINTENANCE_ENDED,
//     SYSTEM_SETTINGS_RESET_TO_DEFAULT, EVENT_DELETED, ADMIN_UPDATED_EVENT_STATUS, ADMIN_VIEW_EVENT_DETAIL, ADMIN_VIEW_EVENT_LIST, ADMIN_DISABLED_USER, ADMIN_ENABLED_USER, ADMIN_UPDATED_VERIFICATION_STATUS, ADMIN_UPDATED_USER_ROLES, ADMIN_VIEW_USER_DETAIL, ADMIN_VIEW_USER_LIST
// }

package com.planbana.backend.audit;

public enum AuditAction {

    // ============================
    // ADMIN ACTIONS
    // ============================
    ADMIN_LOGIN,
    ADMIN_LOGOUT,
    ADMIN_CREATED_USER,
    ADMIN_DELETED_USER,
    ADMIN_UPDATED_USER_PROFILE,
    ADMIN_RESET_USER_PASSWORD,
    ADMIN_UPDATED_USER_ROLE,
    ADMIN_VERIFICATION_APPROVED,
    ADMIN_VERIFICATION_REJECTED,
    ADMIN_REVIEWED_REPORT,

    ADMIN_CREATED_EVENT,
    ADMIN_UPDATED_EVENT_DETAILS,
    ADMIN_DELETED_EVENT,
    ADMIN_BLOCKED_EVENT,
    ADMIN_UNBLOCKED_EVENT,
    ADMIN_HIDDEN_EVENT,
    ADMIN_UNHIDDEN_EVENT,
    ADMIN_APPROVED_EVENT,
    ADMIN_FEATURED_EVENT,

    ADMIN_UPDATED_SYSTEM_SETTINGS,
    ADMIN_UPDATED_FEATURE_FLAGS,
    ADMIN_UPDATED_LIMITS,
    ADMIN_UPDATED_MAINTENANCE_MODE,
    ADMIN_UPDATED_ANNOUNCEMENT,

    // ============================
    // USER ACCOUNT / PROFILE
    // ============================
    USER_REGISTERED,
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    USER_PROFILE_UPDATED,
    USER_PHONE_UPDATED,
    USER_EMAIL_UPDATED,
    USER_PASSWORD_CHANGED,
    USER_ACCOUNT_DISABLED,
    USER_ACCOUNT_REACTIVATED,
    USER_GOV_ID_SUBMITTED,
    USER_GOV_ID_VERIFIED,
    USER_GOV_ID_REJECTED,

    // ============================
    // USER ACTIVITY ON EVENTS
    // ============================
    USER_CREATED_EVENT,
    USER_UPDATED_EVENT,
    USER_DELETED_EVENT,
    USER_BOOKMARKED_EVENT,
    USER_REMOVED_BOOKMARK,
    USER_LEFT_EVENT,
    USER_UPLOADED_EVENT_IMAGE,

    // ============================
    // EVENT LIFE CYCLE
    // ============================
    EVENT_CREATED,
    EVENT_DETAILS_UPDATED,
    EVENT_IMAGE_UPDATED,
    EVENT_LOCATION_UPDATED,
    EVENT_TIME_UPDATED,
    EVENT_CANCELED,
    EVENT_RESTORED,
    EVENT_AUTO_BLOCKED,
    EVENT_AUTO_ARCHIVED,
    EVENT_STARTED,
    EVENT_ENDED,

    // ============================
    // EVENT JOIN / PARTICIPATION
    // ============================
    EVENT_JOIN_REQUESTED,
    EVENT_JOIN_APPROVED,
    EVENT_JOIN_REJECTED,
    EVENT_JOIN_WAITLISTED,
    EVENT_JOIN_CANCELLED,
    EVENT_PARTICIPANT_REMOVED,
    EVENT_COHOST_ADDED,
    EVENT_COHOST_REMOVED,

    // ============================
    // EVENT REACTIONS
    // ============================
    EVENT_LIKED,
    EVENT_UNLIKED,

    // ============================
    // REPORTING & MODERATION
    // ============================
    USER_REPORTED_USER,
    USER_REPORTED_EVENT,
    REPORT_REVIEWED_BY_ADMIN,
    REPORT_ACTION_TAKEN,
    EVENT_FLAGGED_BY_USER,

    // ============================
    // SECURITY & FRAUD
    // ============================
    MULTIPLE_FAILED_LOGIN_ATTEMPTS,
    UNUSUAL_LOCATION_LOGIN,
    TOKEN_TAMPER_DETECTED,
    EXPIRED_TOKEN_USED,
    INVALID_TOKEN_ATTEMPT,
    UNAUTHORIZED_ACCESS_ATTEMPT,
    FORBIDDEN_ADMIN_ACCESS_ATTEMPT,
    API_RATE_LIMIT_EXCEEDED,
    IP_BLOCKED_DUE_TO_ABUSE,
    MULTIPLE_PASSWORD_RESET_REQUESTS,
    SUSPICIOUS_EVENT_SPAM,

    // ============================
    // PAYMENTS
    // ============================
    PAYMENT_INITIATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REFUND_INITIATED,
    REFUND_COMPLETED,

    // ============================
    // INTEGRATIONS
    // ============================
    SMS_SENT,
    PUSH_NOTIFICATION_SENT,
    EMAIL_SENT,
    FAILED_TO_SEND_EMAIL,
    FAILED_TO_SEND_PUSH,
    FIREBASE_LOGIN_FAILURE,

    // ============================
    // SYSTEM
    // ============================
    SYSTEM_CRON_EXECUTED,
    SYSTEM_MAINTENANCE_STARTED,
    SYSTEM_MAINTENANCE_ENDED,
    SYSTEM_SETTINGS_RESET_TO_DEFAULT,

    // Extra event/user actions you added below
    EVENT_DELETED,
    ADMIN_UPDATED_EVENT_STATUS,
    ADMIN_VIEW_EVENT_DETAIL,
    ADMIN_VIEW_EVENT_LIST,
    ADMIN_DISABLED_USER,
    ADMIN_ENABLED_USER,
    ADMIN_UPDATED_VERIFICATION_STATUS,
    ADMIN_UPDATED_USER_ROLES,
    ADMIN_VIEW_USER_DETAIL,
    ADMIN_VIEW_USER_LIST,
    AUTOMATION_KYC_AUTO_REJECTED,
    AUTOMATION_AI_FLAGGED,
    REPORT_THRESHOLD_REACHED,
    ADMIN_RESET_PASSWORD,
    ADMIN_USER_BANNED,
    ADMIN_USER_UNBANNED,
    ADMIN_ADDED_NOTE,
    ADMIN_UPDATED_MODERATOR_SCOPE, ADMIN_ASSIGNED_MODERATOR_REGION, ADMIN_REVIEWED_EVENT_REPORT, ADMIN_ASSIGNED_EVENT, ADMIN_CANCELED_EVENT, ADMIN_ENDED_EVENT, ADMIN_EVENT_NOTE_ADDED, ADMIN_ASSIGNED_REPORT, ADMIN_RESTORED_EVENT, SYSTEM_SETTINGS_UPDATED, ADMIN_UPDATED_ROLES, ADMIN_UPDATED_PROFILE, ADMIN_UNASSIGNED_EVENT,
}
