spring.profiles.active=dev
logging.level.root=INFO
logging.level.com.planbana.backend=DEBUG
logging.level.com.planbana.backend.auth=DEBUG

# Where to store uploaded profile pictures
file.upload-dir=uploads

# ==========================
# Multipart file upload limits
# ==========================
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1524MB


logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.com.planbana.backend.chat=DEBUG
